###Authentication

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

###Teams Endpoints
###Create Team

POST http://localhost:3000/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic3ViIjoxLCJpYXQiOjE3MzU1NTMzNTYsImV4cCI6MTczNTU1Njk1Nn0.Qb6pP2EGClvxY43-zrO86TvSi30zOE_ancfuu1z7i8o
Content-Type: application/json

{
    "name": "frontendTeam",
    "memberIds": ["sandeep", "sandhya"]
}


###Get All Teams

GET http://localhost:3000/teams
Authorization: Bearer <your-jwt-token>


###Update Team

PUT http://localhost:3000/teams/:teamId
Authorization: Bearer <your-jwt-token>
Content-Type: application/json

{
    "name": "Updated Team Name",
    "memberIds": ["member1", "member2", "member3"]
}


###Add Team Member

POST http://localhost:3000/teams/:teamId/members/:memberId
Authorization: Bearer <your-jwt-token>


###Tasks Endpoints
###Create Task

POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic3ViIjoxLCJpYXQiOjE3MzU1NTMzNTYsImV4cCI6MTczNTU1Njk1Nn0.Qb6pP2EGClvxY43-zrO86TvSi30zOE_ancfuu1z7i8o
Content-Type: application/json

{
    "description": "Implement feature X",
    "dueDate": "2025-01-01T00:00:00.000Z",
    "assigneeId": "sandhya",
    "status": "TODO"
}


###Get All Tasks

GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic3ViIjoxLCJpYXQiOjE3MzU1NTMzNTYsImV4cCI6MTczNTU1Njk1Nn0.Qb6pP2EGClvxY43-zrO86TvSi30zOE_ancfuu1z7i8o


###Get Tasks by Assignee

GET http://localhost:3000/tasks/assignee/sandhya
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic3ViIjoxLCJpYXQiOjE3MzU1NTMzNTYsImV4cCI6MTczNTU1Njk1Nn0.Qb6pP2EGClvxY43-zrO86TvSi30zOE_ancfuu1z7i8o


###Update Task

PUT http://localhost:3000/tasks/:taskId
Authorization: Bearer <your-jwt-token>
Content-Type: application/json

{
    "description": "Updated description",
    "status": "IN_PROGRESS"
}
